=== amelhassine/tp1_soa/target/classes/films.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cinema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="films">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="film" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titre" type="xs:string"/>
                                        <xs:element name="annee" type="xs:gYear"/>
                                        <xs:element name="genre" type="xs:string"/>
                                        <xs:element name="realisateur">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="id" type="xs:ID" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="acteurs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="acteur" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amelhassine/tp1_soa/target/classes/films.xml
<?xml version="1.0" encoding="UTF-8"?>
<cinema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="films.xsd">
    <films>
        <film id="f1">
            <titre>Inception</titre>
            <annee>2010</annee>
            <genre>Science-Fiction</genre>
            <realisateur id="cn1">Christopher Nolan</realisateur>
            <acteurs>
                <acteur id="a1">Leonardo DiCaprio</acteur>
                <acteur id="a2">Joseph Gordon-Levitt</acteur>
            </acteurs>
        </film>

        <film id="f2">
            <titre>Interstellar</titre>
            <annee>2014</annee>
            <genre>Science-Fiction</genre>
            <realisateur id="ms1">Martin Scorsese</realisateur>
            <acteurs>
                <acteur id="a3">Matthew McConaughey</acteur>
                <acteur id="a4">Anne Hathaway</acteur>
            </acteurs>
        </film>
    </films>
</cinema>
